services:
  - type: web
    name: monitoring-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
